#!/bin/bash -x

set -euo pipefail
IFS=$'\n\t'

rm -rf /tmp/Alien-nragent

cpanm -n Dist::Zilla


git clone --depth 2 https://github.com/plicease/Alien-nragent.git /tmp/Alien-nragent
cd /tmp/Alien-nragent
dzil authordeps --missing | cpanm -n
dzil listdeps   --missing | cpanm -n
dzil install --install-command 'cpanm -n .'
